### ISSUE TITLE
As someone entering their name to get a permit, I should not be able to enter special characters in my name

### ISSUE THREAD

**Issue by lauraGgit** [nciinc/fs-intake-module#208]
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
Can we clarify the "so that..." part of this story? I'm not sure I understand why we would limit how people enter their names.
