### ISSUE TITLE
As a user I need to know where the harvesting areas are in Shoshone?

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-intake-module#37]
Acceptance Criteria
 - harvesting areas are defined clearly as an image (map) indicating harvest areas or a textual description
- download link allowing user to potentially print/save the map/info
- harvesting areas are defined clearly as text when no map exists

Definition of Done

 - [ ] Server Code unit / e2e tested and comply with QWASP (Cameron)
 - [ ] Frontend Code unit tested and comply with QWASP
 - [ ] Frontend Code e2e tested and comply with QWASP
 - [ ] No new security vulnerabilities
 - [ ] Team code review
 - [ ] Documentation / readme.md / CircleCI updated
 - [ ] Docker updated
 - [ ] Compare finished design with mockup (Bryan)
 - [ ] Usability tested (Bryan)

Tasks

- [ ] research existing pilot forest information
- [ ] get maps as pdfs
- [ ] create thumbnail images for maps (seth)
- [ ] final approval of content (Amber & Colin)
- [ ] editing/creation of content (Jane and Amber)
- [ ]  modify wireframe for text only location description
- [ ] add new location information into the seeders for Flathead
- [ ] usability testing of the content (Bryan, Colin)
- [ ] modifications based on usability results
- [ ] e2e tests changes to include screenshots (Shekar)
- [ ] add org_structure_code to forests (Shekar)
- [ ] a11y

**Comment by JaneZC** [comment]
Some potential content issues to be addressed in the future or via usability:

- The map for Shoshone mentions specific places the public can buy paper permits. Should this be changed?
- Is the light-green area on the map (Washakie district) the only place in Shoshone that has Christmas tree cutting.
- Missing textural description of that area; we will develop one but it to be checked.
