### ISSUE TITLE
As a user I need to quickly and clearly be able to locate information in the navigation

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-intake-module#92]
Acceptance Criteria

Tasks
[ ] - change title to Blah National Forest Christmas Tree Information
[ ] - remove places to try header - leave be on national forest land
[ ] - edit top section and replace with what Amber provides
[ ] - remove the paragraph under Where to find your tree
[ ] - add search to allow users to search on keywords throughout the website

**Comment by ASprinkle** [comment]
Underneath the large green introductory header, include the following welcoming message "Your Christmas tree permit will allow you to cut a tree on the XX National Forest following the rules and regulations on your permit, you may cut a Christmas on the Forest, except as noted below in PROHIBITED information sections."
